apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-java-app
  template:
    metadata:
      labels:
        app: demo-java-app
    spec:
      containers:
      - name: demo-java-app
        image: hajarek24/demo-java-app:1.0
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: demo-java-app
spec:
  type: NodePort
  selector:
    app: demo-java-app
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081