apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-java-app
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: demo-java-app
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s